name: eikyo
version: 0.1.0.0
github: "dannypsnl/eikyo"
license: BSD3
author: "dannypsnl"
maintainer: "dannypsnl@gmail.com"
copyright: "2022 dannypsnl"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dannypsnl/eikyo#readme>

dependencies:
  - base >= 4.7 && < 5
  # command line arg parsing
  - cmdargs >= 0.10
  # language parser
  - text >= 1.2
  - megaparsec >= 9.2
  - parser-combinators >= 1.3

library:
  source-dirs: src

default-extensions:
  - DuplicateRecordFields
  - NamedFieldPuns
  - RecordWildCards
  - OverloadedStrings
  - QuasiQuotes

executables:
  eikyo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - eikyo

tests:
  eikyo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - eikyo
      - hspec
      - hspec-megaparsec
      - template-haskell
